version: '3'

services:
  # Database
  db:
    image: jsurf/rpi-mariadb
    volumes:
      - db_data:/var/lib/mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: hardpassw

  # Datasaver
  datasaver:
    depends_on:
      - db
    build: .
    DB: db
    SENSOR: "http://192.168.51.55"
    restart: unless-stopped

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: ebspace/armhf-phpmyadmin
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password

volumes:
  db_data:
